"""Tests for AudioTagger Picard-compatible reads across FLAC/MP3/M4A.

Reads the committed fixtures in ``tests/fixtures/library/`` (generated by
``generate.py`` with raw mutagen - an independent oracle).
"""

import shutil
from pathlib import Path

import pytest

from infrastructure.audio.tagger import AudioTagger

FIXTURES = Path(__file__).resolve().parent.parent / "fixtures" / "library"


@pytest.fixture
def tagger() -> AudioTagger:
    return AudioTagger()


@pytest.fixture
def tmp_copy(tmp_path: Path):
    def _copy(name: str) -> Path:
        dest = tmp_path / name
        shutil.copy(FIXTURES / name, dest)
        return dest

    return _copy


# -- read: Picard MBID mapping per format --


def test_read_flac_release_group_id(tagger):
    tag, _ = tagger.read_tags(FIXTURES / "flac_full_01.flac")
    assert tag.musicbrainz_release_group_id == "b1392450-e666-3926-a536-22c65f834433"


def test_read_mp3_release_group_id(tagger):
    tag, _ = tagger.read_tags(FIXTURES / "mp3_full_01.mp3")
    assert tag.musicbrainz_release_group_id == "rg-achtung-0001"


def test_read_m4a_release_group_id(tagger):
    tag, _ = tagger.read_tags(FIXTURES / "m4a_full_01.m4a")
    assert tag.musicbrainz_release_group_id == "rg-mezzanine-0001"


def test_read_flac_all_mbid_fields(tagger):
    tag, _ = tagger.read_tags(FIXTURES / "flac_full_01.flac")
    assert tag.musicbrainz_release_id == "0da3b3e3-1111-4444-8888-aaaaaaaaaaaa"
    assert tag.musicbrainz_recording_id == "rec-airbag-0001"
    assert tag.musicbrainz_artist_id == "a74b1b7f-71a5-4011-9441-d0b5e4122711"
    assert tag.acoustid_id == "ac-airbag-0001"


def test_read_descriptive_fields(tagger):
    tag, _ = tagger.read_tags(FIXTURES / "flac_full_01.flac")
    assert (tag.title, tag.artist, tag.album, tag.album_artist) == (
        "Airbag",
        "Radiohead",
        "OK Computer",
        "Radiohead",
    )
    assert tag.track_number == 1
    assert tag.year == 1997


def test_read_rich_metadata_from_independently_written_flac_tags(tagger, tmp_copy):
    from mutagen.flac import FLAC

    path = tmp_copy("flac_full_01.flac")
    audio = FLAC(path)
    audio["TITLESORT"] = "Airbag, The"
    audio["ARTISTSORT"] = "Radiohead"
    audio["ALBUMSORT"] = "OK Computer"
    audio["ALBUMARTISTSORT"] = "Radiohead"
    audio["DISCSUBTITLE"] = "Bonus Disc"
    audio["ORIGINALDATE"] = "1997-05-21"
    audio["REPLAYGAIN_TRACK_GAIN"] = "-7.25 dB"
    audio["REPLAYGAIN_ALBUM_GAIN"] = "-6.50 dB"
    audio["REPLAYGAIN_TRACK_PEAK"] = "0.987"
    audio["REPLAYGAIN_ALBUM_PEAK"] = "0.999"
    audio.save()

    tag, _ = tagger.read_tags(path)

    assert tag.title_sort == "Airbag, The"
    assert tag.disc_subtitle == "Bonus Disc"
    assert tag.original_release_date == "1997-05-21"
    assert tag.replaygain_track_gain == -7.25
    assert tag.replaygain_album_gain == -6.5
    assert tag.replaygain_track_peak == 0.987
    assert tag.replaygain_album_peak == 0.999


def test_read_audio_info(tagger):
    _, info = tagger.read_tags(FIXTURES / "flac_full_01.flac")
    assert info.file_format == "flac"
    assert info.sample_rate == 44100
    assert info.bit_depth == 16  # FLAC is lossless
    assert info.channels == 2
    assert info.file_size_bytes > 0


def test_read_mp3_info_has_no_bit_depth(tagger):
    _, info = tagger.read_tags(FIXTURES / "mp3_full_01.mp3")
    assert info.file_format == "mp3"
    assert info.bit_depth is None  # lossy


def test_read_m4a_info_has_no_bit_depth(tagger):
    # MP4Info.bits_per_sample is 16 even for lossy AAC - must be suppressed.
    _, info = tagger.read_tags(FIXTURES / "m4a_full_01.m4a")
    assert info.file_format == "m4a"
    assert info.bit_depth is None


# -- read: compilation flag per format --


def test_compilation_flag_flac(tagger):
    tag, _ = tagger.read_tags(FIXTURES / "flac_compilation_01.flac")
    assert tag.compilation is True
    assert tag.album_artist == "Various Artists"


def test_non_compilation_flag(tagger):
    tag, _ = tagger.read_tags(FIXTURES / "flac_full_01.flac")
    assert tag.compilation is False


# -- read: edge cases --


def test_mp3_recording_id_is_stored_as_ufid_not_release_track(tagger, tmp_copy):
    # The recording MBID must live in the UFID frame (Picard), never the
    # "Release Track Id" TXXX - that's a different MusicBrainz entity.
    import mutagen

    raw = mutagen.File(tmp_copy("mp3_full_01.mp3"))
    assert "UFID:http://musicbrainz.org" in raw.tags
    assert "TXXX:MusicBrainz Release Track Id" not in raw.tags


def test_only_release_mbid_leaves_release_group_none(tagger):
    tag, _ = tagger.read_tags(FIXTURES / "flac_only_release_mbid.flac")
    assert tag.musicbrainz_release_group_id is None
    assert tag.musicbrainz_release_id == "rel-only-0001"


def test_cjk_tags_preserved(tagger):
    tag, _ = tagger.read_tags(FIXTURES / "flac_cjk_01.flac")
    assert tag.artist == "ユキ"
    assert tag.title == "桃源へ"


def test_no_tags_yields_empty_strings(tagger):
    tag, _ = tagger.read_tags(FIXTURES / "flac_no_tags.flac")
    assert tag.title == ""
    assert tag.artist == ""
    assert tag.musicbrainz_release_group_id is None


def test_unreadable_file_raises(tagger, tmp_path):
    junk = tmp_path / "not-audio.flac"
    junk.write_bytes(b"this is not audio")
    with pytest.raises(ValueError):
        tagger.read_tags(junk)


# -- multi-value genre reads surface every value --


def _set_genres(path: Path, genres: list[str]) -> None:
    """Write multiple genre values with raw mutagen (an independent oracle)."""
    import mutagen
    from mutagen.id3 import TCON
    from mutagen.mp3 import MP3
    from mutagen.mp4 import MP4

    audio = mutagen.File(path)
    if isinstance(audio, MP4):
        audio.tags["\xa9gen"] = genres
    elif isinstance(audio, MP3):
        audio.tags.setall("TCON", [TCON(encoding=3, text=genres)])
    else:
        audio["GENRE"] = genres
    audio.save()


@pytest.mark.parametrize(
    "name", ["flac_full_01.flac", "mp3_full_01.mp3", "m4a_full_01.m4a"]
)
def test_read_multi_genre_surfaces_all_values(tagger, tmp_copy, name):
    path = tmp_copy(name)
    _set_genres(path, ["Rock", "Jazz", "Electronic"])
    tag, _ = tagger.read_tags(path)
    assert tag.genre == "Rock; Jazz; Electronic"
    assert tag.genres == ["Rock", "Jazz", "Electronic"]


@pytest.mark.parametrize(
    "name", ["flac_full_01.flac", "mp3_full_01.mp3", "m4a_full_01.m4a"]
)
def test_read_picard_artist_values_without_splitting_joined_credit(
    tagger, tmp_copy, name
):
    import mutagen
    from mutagen.id3 import TPE1, TXXX
    from mutagen.mp3 import MP3
    from mutagen.mp4 import MP4

    path = tmp_copy(name)
    audio = mutagen.File(path)
    if isinstance(audio, MP4):
        audio.tags["\xa9ART"] = ["Artist A feat. Artist B"]
        audio.tags["----:com.apple.iTunes:ARTISTS"] = [b"Artist A", b"Artist B"]
        audio.tags["----:com.apple.iTunes:MusicBrainz Artist Id"] = [
            b"artist-a",
            b"artist-b",
        ]
    elif isinstance(audio, MP3):
        audio.tags.setall("TPE1", [TPE1(encoding=3, text=["Artist A feat. Artist B"])])
        audio.tags.setall(
            "TXXX:Artists",
            [TXXX(encoding=3, desc="Artists", text=["Artist A", "Artist B"])],
        )
        audio.tags.setall(
            "TXXX:MusicBrainz Artist Id",
            [
                TXXX(
                    encoding=3,
                    desc="MusicBrainz Artist Id",
                    text=["artist-a", "artist-b"],
                )
            ],
        )
    else:
        audio["ARTIST"] = ["Artist A feat. Artist B"]
        audio["ARTISTS"] = ["Artist A", "Artist B"]
        audio["MUSICBRAINZ_ARTISTID"] = ["artist-a", "artist-b"]
    audio.save()

    tag, _ = tagger.read_tags(path)

    assert tag.artist == "Artist A feat. Artist B"
    assert [credit.name for credit in tag.artists] == ["Artist A", "Artist B"]
    assert tag.musicbrainz_artist_ids == ["artist-a", "artist-b"]


def test_single_scalar_artist_with_punctuation_remains_one_credit(tagger, tmp_copy):
    from mutagen.flac import FLAC

    path = tmp_copy("flac_full_01.flac")
    audio = FLAC(path)
    audio["ARTIST"] = ["Alpha; Beta"]
    if "ARTISTS" in audio:
        del audio["ARTISTS"]
    audio.save()

    tag, _ = tagger.read_tags(path)

    assert [credit.name for credit in tag.artists] == ["Alpha; Beta"]
